config/routes.rb
Craiglistnew::Application.routes.draw do
  resources :categories
  resources :responses
  resources :users
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  get "static_pages/home"
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/contact', to: 'static_pages#_contact', via: 'get'
  match '/buscar', to: 'static_pages#buscar', via: 'get'
  get "users/new"
  get "users/index"
  get 'admin' => 'admin#dashboard', as: :admin

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @post  = current_user.posts.build
      if !params[:category].nil?
        @posts = Post.where(category_id:params[:category][:category_id]).paginate(page: params[:page]).where(approved:true)
      else
        @posts = Post.where(approved:true).paginate(page: params[:page])
      end

    else
      if !params[:category].nil?
      @posts = Post.where(category_id:params[:category][:category_id]).paginate(page: params[:page]).where(approved:true)
      else
        @posts = Post.where(approved:true).paginate(page: params[:page])
      end
    end
  end
  def buscar
    @posts = Post.where(:category_id,params[:category_id])
    redirect_to root_path
  end

  def help
  end

  def about
  end

  def _contact

  end
end

app/views/static_pages/_contact.html.erb
<%= form_for(@response) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email_visitor %>
    </div>
    <div class="field">
      <%= f.text_area :content_visitor, placeholder: "Compose new response..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/static_pages/home.html.erb
<h3>CraigList Minimal</h3>
<%= form_tag("/home", method: "get") do %>
    <%= label_tag(:name, "Search for:") %>
    <%= collection_select(:category, :category_id, Category.all, :id, :name) %>
    <%= submit_tag("Apply") %><%= link_to "  Show all  ", root_path %>
<% end %>

<% if signed_in? %>
    <div class="microposts">

        <section>
          <%= render 'shared/user_info' %>
        </section>
        <section>
          <% @posts.each do |post| %>
              <div class="img"><%= image_tag post.photo.url %><li>
            <span class="content"><%= post.content %></span>
            <span class="timestamp">
            Posted <%= time_ago_in_words(post.created_at) %> ago..<br>
            Create by <%= link_to post.user.name, post_path(post) %> <br>
            Category <%= post.category.name %>
             </span>
                <% if current_user?(post.user) %>
                    <%= link_to "delete", post, method: :delete,
                                data: { confirm: "You sure?" },
                                title: post.content %>
                <% end %>
              </li></div>
          <% end %>
        </section>
        <section>
          <%= render 'shared/post_form' %>
        </section>

    </div>
<% else %>
    <div class="microposts">
      <section>
        <% @posts.each do |post| %>
            <div class="img"><%= image_tag post.photo.url %><li>
           <span class="content"><%= post.content %></span>
            <span class="timestamp">
            Posted <%= time_ago_in_words(post.created_at) %> ago.<br>
            Contact to <%= link_to post.user.name, post_path(post) %><br>
            Category <%= post.category.name %>
             </span>
              <% if current_user?(post.user) %>
                  <%= link_to "delete", post, method: :delete,
                              data: { confirm: "You sure?" },
                              title: post.content %>
              <% end %>
            </li>    </div>
        <% end %>
      </section>
      <%= link_to "Sign up now!", signup_path,
                  class: "btn btn-large btn-primary" %>
    </div>
<% end %>