config/routes.rb
Craiglistnew::Application.routes.draw do
  resources :categories
  resources :responses
  resources :users
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  get "static_pages/home"
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/contact', to: 'static_pages#_contact', via: 'get'
  match '/buscar', to: 'static_pages#buscar', via: 'get'
  get "users/new"
  get "users/index"
  get 'admin' => 'admin#dashboard', as: :admin

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :responses
  belongs_to :user
  belongs_to :category
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  has_attached_file :photo, :default_url => "descarga.jpg"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :edit]
  before_action :correct_user,   only: :destroy
  before_action :admin_user,     only: [:destroy]
  def index
    if !params[:category].nil?
      @posts = Post.where(category_id:params[:category][:category_id]).paginate(page: params[:page]).where(approved:nil)
    else
      @posts = Post.where(approved:nil).paginate(page: params[:page])
    end

  end
  def create
    @post = current_user.posts.build(post_params)
    @post.category_id = params[:category][:category_id]
    if @post.save
      flash[:success] = "post created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  def edit
    @post = Post.find(params[:id])
  end
  def show
    @post = Post.find(params[:id])
    @response = Response.new
  end
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_url
  end

  private

  def post_params
    params.require(:post).permit(:content,:approved,:photo)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end


end

app/views/posts/_posts.html.erb
  <div class="img">
  <%= image_tag post.photo.url %><li>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
  <% if current_user?(post.user) %>
      <%= link_to "delete", post, method: :delete,
                  data: { confirm: "You sure?" },
                  title: post.content %>
  <% end %>
</li></div>


app/views/posts/edit.html.erb
<% provide(:title, "Edit post") %>
<h1>Update </h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@post) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        User post <%= @post.user.name %><br>
        <br><%= f.label :content %>
        <br><%= f.text_field :content %>

        <% if current_user.admin? %>
            <div class="field">
              <%= f.label :approved %><br>
              <%= f.check_box :approved %>
            </div>  <br>
        <% end %>
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>Listing adverts</h1>
<br>
<%= form_tag("/posts", method: "get") do %>
    <%= label_tag(:name, "Search for:") %>
    <%= collection_select(:category, :category_id, Category.all, :id, :name) %>
    <%= submit_tag("Apply") %><%= link_to "  Show all  ", posts_path %>
<% end %>
<table>
  <thead>
  <tr>
    <th>User</th>
    <th>Description</th>
    <th>Category</th>
    <th>Approved</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= post.content %></td>
        <td><%= post.category.name %></td>
        <td><%= post.approved %></td>
        <% if current_user.admin? %>
            <td><%= link_to 'Show', post_path(post) %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if session[:current_user_id] %>
    <%= link_to 'New Advert', new_advert_path %>
<% else %>
    <%= link_to 'Register', new_user_path %>
    <%= link_to "Back", root_path %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @post.photo.url %>
</p>
<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<section>
  <h1>Response</h1>
  <%= render 'shared/contact_form' %>
</section>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', root_path %>