config/routes.rb
Craiglistnew::Application.routes.draw do
  resources :categories
  resources :responses
  resources :users
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  get "static_pages/home"
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/contact', to: 'static_pages#_contact', via: 'get'
  match '/buscar', to: 'static_pages#buscar', via: 'get'
  get "users/new"
  get "users/index"
  get 'admin' => 'admin#dashboard', as: :admin

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

  </small>
  <nav>
    <ul>


    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "advertisements", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", home_path %></li>

          <% if signed_in? %>
              <% if current_user.admin? %>
              <li><%= link_to "Admin", admin_path %></li>
              <% end %>
              <%= link_to "Sign out", signout_path, method: "delete" %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu" >
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>


                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minimal CraigList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>